### ISSUE TITLE
Is this different from gulp-changed?  

### ISSUE THREAD

**Issue by BurtHarris** [TypeForce/vinyl-not-modified#1]
gulp-changed and/or gulp-newer?

**Comment by samvv** [comment]
Yes, it works reversely: it checks the output files instead of the input files and only passes through if it is **not** changed. Still needs some work though.

**Comment by samvv** [comment]
@BurtHarris thanks for letting me know of `gulp-changed`; it led me to [gulp-remember](https://github.com/ahaurw01/gulp-remember), which I think solves a problem I am currently having 😄

**Comment by BurtHarris** [comment]
Sure thing.   The [gulp guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) are excellent reading.
